---
deployment:
  tasks:
    - /usr/local/cpanel/3rdparty/bin/git -C /home/gochess/gochess_repo fetch origin main
    - /usr/local/cpanel/3rdparty/bin/git -C /home/gochess/gochess_repo reset --hard origin/main
    - /usr/local/cpanel/3rdparty/bin/git -C /home/gochess/gochess_repo clean -fd
    - /bin/cp -Rf /home/gochess/gochess_repo/dist/. /home/gochess/public_html/